### ISSUE TITLE
Return parens added in some cases if preserveDotChain is enabled despite returnParentheses being disabled

### ISSUE THREAD

**Issue by nocnokneo** [Yikes2000/prettier-plugin-merge-extras#2]
## Steps to reproduce

With a `.prettierrc.yaml` like:

```yaml
semi: false
alignObjectProperties: none
preserveFirstBlankLine: false
preserveLastBlankLine: false
returnParentheses: false
preserveDotChain: true
plugins:
  - prettier-plugin-sh
  - prettier-plugin-tailwindcss
  - "@yikes2000/prettier-plugin-merge-extras"
```

With a TS file containing:

```ts
  return spec()
    .use("gqlPost")
    .use("superUserAuth", { override: tokenOverride })
    .use("gqlQuery", {
      query: `
          ${fragment}
          ${query}
        `,
      variables,
      expectError,
    })
```

I get:

```ts
  return (
    spec()
      .use("gqlPost")
      .use("superUserAuth", { override: tokenOverride })
      .use("gqlQuery", {
        query: `
          ${fragment}
          ${query}
        `,
        variables,
        expectError,
      })
  )
```

If I change `preserveDotChain` to `false` then the problem goes away (return parens don't get added), but then I don't get the feature that brought me to prettier-plugin-merge-extras :-)
