### ISSUE TITLE
Does this work with prettier-java?

### ISSUE THREAD

**Issue by SimonCockx** [Yikes2000/prettier-plugin-merge-extras#5]
I am currently trying to use this plugin for a Java project to preserve method chaining. Is there something wrong with my configuration, or is this just not supported?

Versions:
``` json
 "devDependencies": {
    "@prettier/plugin-xml": "^3.3.1",
    "@yikes2000/prettier-plugin-merge-extras": "^0.7.1-extras.4",
    "husky": "^9.0.11",
    "lint-staged": "^15.2.2",
    "prettier": "^3.4.2",
    "prettier-plugin-java": "^2.5.0",
    "prettier-plugin-kotlin": "^2.1.0"
  },
```

Here is my `.prettierrc.yaml`:
``` yaml
plugins:
  - '@yikes2000/prettier-plugin-merge-extras' # this plugin must be positioned last (according to the docs)
trailingComma: none
useTabs: false
tabWidth: 2
printWidth: 150
arrowParens: avoid
endOfLine: auto
# prettier-plugin-merge-extras options: https://www.npmjs.com/package/@yikes2000/prettier-plugin-merge-extras?activeTab=readme
alignObjectProperties: none
mergeSimpleImports: true
preserveDotChain: true
preserveEolMarker: true
preserveFirstBlankLine: false
preserveLastBlankLine: false
returnParentheses: true
```

However, this does not seem to be working. My code:
``` java
exceptionMsg
          .append("\n")
          .append(i + 1)
          .append(". ")
          .append(formatDiagnostic(diagnostic).replace("\n", "\n   "));
```
is still being converted to
``` java
exceptionMsg.append("\n").append(i + 1).append(". ").append(formatDiagnostic(diagnostic).replace("\n", "\n   "));
```
